name: clang-tidy linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Install tooling
        run: sudo apt update && sudo apt install clang-tidy

      - name: Run linting
        run: echo test
