name: cpp-linter.yml
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          ignore: 'CANopenNode/|CANopenNode_STM32/|Drivers/|Middlewares/'
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "::error::${{steps.linter.outputs.checks-failed}} Linting failed. Please fix before merging."
          exit 1
