name: cpp-linter.yml
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi ninja-build
      - name: Generate compile_commands
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --preset Debug
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          database: 'build/Debug'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          ignore: 'Drivers/STM32G4xx_HAL_Driver/|Middlewares/|SMBus_PMBus_Stack/|Core/|build/|AZURE_RTOS/'
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "::error:: Linting failed. Please fix before merging."
          exit 1
